### ISSUE TITLE
Useful for source map for AI tool?

### ISSUE THREAD

**Issue by minthemiddle** [cathaysia/tree-sitter-loongdoc#27]
I'm looking for treesitter for Asciidocs for adding support for Asciidoc in aider (a pair programming AI tool).
The tree sitter is used to create repo maps that are then used as context.
My thought was that headlines might be similar to function names and would be useful to be passed to context when writing.

How do you use this tree sitter here?  
Do you think it could be used for this case?  

Here are some links with context:  

- https://aider.chat/docs/repomap.html
- https://aider.chat/

**Comment by cathaysia** [comment]
In fact, the reason I create this repo is to provide code highlight in neovim. I think you can use this repo in your case. But from my experience with tree-sitter-idl, almost all commits that cause ast changes will cause breaking changes. I think you may need to design your code carefully. Avoid large-scale code updates caused by tree-sitter-asciidoc updates
